"""initial migration with team_schedules table

Revision ID: 08884eccda76
Revises: 
Create Date: 2025-10-15 22:10:40.369098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08884eccda76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_date', sa.String(length=10), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_name', sa.String(length=100), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_schedules_game_date'), 'team_schedules', ['game_date'], unique=False)
    op.create_index(op.f('ix_team_schedules_game_id'), 'team_schedules', ['game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_schedules_game_id'), table_name='team_schedules')
    op.drop_index(op.f('ix_team_schedules_game_date'), table_name='team_schedules')
    op.drop_table('team_schedules')
    # ### end Alembic commands ###
